### ISSUE TITLE
Rename HTML File to index.html

### ISSUE THREAD

**Issue by michael-shattuck** [scottds/KB-Design#1]
The file name "HTML File" needs to have an `.html` extension. This defines it as an html file.
Also, it is generally good practice to name the entry point page `index.html`.

**Comment by scottds** [comment]
Does saving it as something.html not give it an .html extension? For example, KB Design.html is an html file, right? Or am I misunderstanding that? 

As for having it named index.html, I find that annoying. If every project's html file is named index.html, wouldn't it get confusing?
